baseURL = 'https://www.cybernotes.uk/'
languageCode = 'en-us'
title = 'Cybernotes'
theme = 'hugo-PaperMod'
paginate = 3

[[menu.main]]
identifier = "About"
name = "â„¹ï¸ About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "Archives"
name = "ğŸ“ Archives"
url = "/archives/"
weight = 2

[[menu.main]]
identifier = "Tags"
name = "ğŸ·ï¸ Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "Useful"
name = "âœ… Useful"
url = "/useful/"
weight = 4

[[menu.main]]
identifier = "Tools"
name = "ğŸª› Tools"
url = "/tools/"
weight = 5

[[menu.main]]
identifier = "CTF"
name = "ğŸš© CTF"
url = "/ctf/"
weight = 6

[[menu.main]]
identifier = "Cryptography"
name = "ğŸ”’ Cryptography"
url = "/cryptography/"
weight = 7

[[menu.main]]
identifier = "Blog"
name = "ğŸ“ Blog"
url = "/posts/"
weight = 8

[[menu.main]]
identifier = "Search"
name = "ğŸ” Search"
url = "/search/"
weight = 9

[[menu.main]]
identifier = "Linkedin"
name = "ğŸŒ Linkedin"
url = "https://www.linkedin.com/company/cybernotes"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[params]
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

env = "production"
defaultTheme = "dark"
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ]
disableThemeToggle = true

  [params.profileMode]
  enabled = true
  title = ""
  imageUrl = "cybernotes_logo.jpg"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  #[params.homeInfoParams]
  #Title = ""
  #Content = """
#Welcome to my blog. Here you will find topics in Cyber Security, that range from Penetration Testing, Bug Bounty, CTF and more.
#"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/mariosdaskalas/mariosdaskalas.github.io"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/company/cybernotes/"

[params.label]
icon = "/static/cybernotes.jpg"
